### ISSUE TITLE
Support more languages

### ISSUE THREAD

**Issue by thieung** [aaronhallaert/continuous-testing.nvim#28]
Thanks for awesome plugins.
In order to integrate new language (e.g: go, dart, ...), do you have a document for that?

**Comment by aaronhallaert** [comment]
I have some kind of guide in the vim-docs (tag: `continuous-testing.test_frameworks`). I just merged an update to the doc.
https://github.com/aaronhallaert/continuous-testing.nvim/blob/ff2c46f06247df3b0b02217b163211487f68cdcd/doc/continuous-testing.txt#L31
Make sure to have a look at the `ruby/rspec` implementation as a reference.
